name: First Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ AWS_SESSION_TOKEN }}
    steps:
      - run: echo "Hello World!"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in repository
        run: |
          echo "Trying to use AWS CLI"
          aws ec2 describe-instances --region us-east-1

          
